"""Sphinx configuration for the Kandra documentation site.

Run locally with ``make serve-docs`` (live reload at http://localhost:8000)
or build a one-shot static site with ``make build-docs``.

Conventions:

- All authoring is in Markdown via MyST-Parser; no reStructuredText required.
- Diagrams are Mermaid (sequence + class). No PlantUML / Java dependency.
- API reference is autogenerated from docstrings via ``sphinx.ext.autodoc``
  + ``autodoc-pydantic`` (rich rendering of Pydantic v2 models).
- Theme is Furo (clean, dark/light toggle, sidebar tree).
"""

from __future__ import annotations

import sys
from pathlib import Path

# Make both packages importable so autodoc can introspect type hints.
# The editable install also exposes them, but adding the source dirs
# explicitly keeps Sphinx working in environments where only the source
# tree is available (e.g. ReadTheDocs without the venv).
_REPO_ROOT = Path(__file__).resolve().parents[1]
_PKG_ROOT = _REPO_ROOT / "packages"
sys.path.insert(0, str(_PKG_ROOT / "kandra-runtime" / "src"))
sys.path.insert(0, str(_PKG_ROOT / "kandra" / "src"))

# -- Project information -----------------------------------------------------
project = "Kandra"
author = "Sean Foley"
release = "0.0.1"

# -- General configuration ---------------------------------------------------
extensions = [
    "myst_parser",                  # Markdown source files
    "sphinx.ext.autodoc",           # Pull docstrings into pages
    "sphinx.ext.napoleon",          # Google / NumPy docstring styles
    "sphinx.ext.intersphinx",       # Cross-link to upstream docs
    "sphinx.ext.viewcode",          # "[source]" links next to APIs
    "sphinxcontrib.mermaid",        # ```mermaid fenced blocks
    "sphinxcontrib.autodoc_pydantic",  # Rich Pydantic v2 rendering
    "sphinx_copybutton",            # Copy-to-clipboard on code blocks
    "sphinx_design",                # Tabs / cards / grids
]

# Markdown extensions (MyST) ------------------------------------------------
myst_enable_extensions = [
    "colon_fence",       # ```{note} ...
    "deflist",           # Definition lists
    "fieldlist",         # :field: lists
    "tasklist",          # - [ ] checkboxes
    "attrs_inline",      # {.class #id} on inline elements
    "smartquotes",       # Curly quotes
]
myst_heading_anchors = 3            # Auto-generate slug anchors for h1-h3

source_suffix = {
    ".md": "markdown",
    ".rst": "restructuredtext",
}

exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
templates_path = ["_templates"]

# -- HTML output -------------------------------------------------------------
html_theme = "furo"
html_static_path = ["_static"]
html_title = f"{project} {release}"
html_theme_options = {
    "sidebar_hide_name": False,
    "navigation_with_keys": True,
    # TODO: set the public repository URL once the project has a home, then
    # re-enable the source-link options below (they add "edit source" links).
    # "source_repository": "https://github.com/OWNER/kandra/",
    # "source_branch": "main",
    # "source_directory": "docs/",
}

# Force dark mode as the default. Furo has no built-in "default theme"
# option, so we inject a tiny script that flips the data-theme attribute
# on first visit. Users can still toggle via the sun/moon icon; their
# choice is persisted in localStorage.
html_js_files = ["force_dark_default.js"]

# Dark Mermaid theme so diagrams stay readable on the default dark background.
mermaid_init_js = (
    "mermaid.initialize({startOnLoad:true, theme:'dark', "
    "themeVariables:{darkMode:true, background:'#131416'}});"
)

# -- Autodoc -----------------------------------------------------------------
autodoc_default_options = {
    "members": True,
    "show-inheritance": True,
    "undoc-members": False,
    "member-order": "bysource",
}
autodoc_typehints = "description"   # Move type hints into the description body

# Pydantic autodoc tuning -- show validators + discriminators clearly.
autodoc_pydantic_model_show_json = False
autodoc_pydantic_model_show_config_summary = False
autodoc_pydantic_model_show_field_summary = True
autodoc_pydantic_model_show_validator_summary = True
autodoc_pydantic_field_list_validators = True
autodoc_pydantic_field_show_constraints = False  # regex like [a-z0-9] confuses RST

# -- Intersphinx -------------------------------------------------------------
# Auto-link any mention of e.g. `aiohttp.ClientSession` to its upstream docs.
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "pydantic": ("https://docs.pydantic.dev/latest/", None),
    "aiohttp": ("https://docs.aiohttp.org/en/stable/", None),
}
# Don't fail the build if upstream inventories are unreachable (offline /
# corporate proxy / CDN 403). Cross-links degrade to plain text.
intersphinx_disabled_reftypes = ["*"]
intersphinx_timeout = 5

# Quiet warnings that come from third-party docstrings we don't control.
# NOTE: keep this list narrow — over-suppression hides real typos in xrefs.
# `myst.xref_missing` is currently NOT suppressed; broken intra-doc links
# will still warn (and fail `make build-docs-strict`). Add entries here
# only with a comment explaining the source.
suppress_warnings: list[str] = []

# -- Mermaid -----------------------------------------------------------------
mermaid_version = "10.9.0"          # Pinned for reproducible builds
